#!/bin/sh

if ! command -v haskell >/dev/null 2>&1; then
    echo "No haskell-clean-compile on the system" >&2
    exit 1
fi

CWD=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd) || exit 1
(cd "$CWD" && haskell algebra.hs main.hs)
