#!/bin/sh

ASSERT ()
{
    if ! "$@"; then
        echo "Assertion failed: $@" >&2
        exit 1
    fi
}

CWD=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd) || exit 1
ASSERT "$CWD/scalarMain"
ASSERT "$CWD/vectorMain"
